version: 1.0
workflows:
  android:
    name: Android Build
    max_build_duration: 60
    scripts:
      - name: Build APK
        script: ./gradlew assemble
    artifacts:
      - app/build/outputs/apk/release/*.apk
